### ISSUE TITLE
Missing requests in requirements

### ISSUE THREAD

**Issue by LinusU** [rSkogeby/item-catalog#1]
Seems like `requests` is missing from `requirements.txt` 🤔 

<img width="609" alt="Screenshot 2019-03-13 at 18 12 24" src="https://user-images.githubusercontent.com/189580/54303754-a02cc400-45bb-11e9-86e6-4175b25de616.png">

**Comment by rSkogeby** [comment]
Thanks for the heads up, needs to be added to the README.md as well so I'll go ahead and do that!

**Comment by LinusU** [comment]
Just my personal opinion ☺️ but why are you also listing the requirements in the readme? 🤔

**Comment by rSkogeby** [comment]
To give other users an eagle eye view over what modules are used in the web app. It does come across as a bit redundant I must agree :sweat_smile:
