### ISSUE TITLE
No way to listen to all interfaces

### ISSUE THREAD

**Issue by LinusU** [rSkogeby/item-catalog#4]
The app always listens to `localhost`, which means that there is no way to contact it from the outside when running e.g. in Docker, or on EC2, etc.

Would be nice with an env variable to control which interface to listen to, which can default to `localhost` so that no-one unintentionally opens up their app to the world ☺️

That way it will just be an env-switch when deploying à la `LISTEN_INTERFACE=0.0.0.0`

**Comment by LinusU** [comment]
Could potentially be nice to be able to specify port as well, Docker already handles that but EC2 won't be able to co-host applications using the same port.

e.g. `LISTEN_PORT=1337`

**Comment by rSkogeby** [comment]
Thanks for the suggestion, I'll add it straight away!
